apiVersion: v1
kind: Namespace
metadata:
  name: bat-utility
---
apiVersion: v1
kind: Pod
metadata:
  name: control-panel-pod
  namespace: bat-utility
spec:
  containers:
  - name: control-panel-container
    image: localhost:5000/control-panel:latest
    securityContext:
      privileged: true
    volumeMounts:
    - name: gpiomem4-device
      mountPath: /dev/gpiomem
  volumes:
  - name: gpiomem4-device
    hostPath:
      path: /dev/gpiomem
      type: CharDevice